name: Automated Tests

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  
          yarn install  

      - name: Run UI Tests
        run: python uiTesting.py  

      - name: Run API Tests
        run: python apiTesting.py  
